language: node_js
node_js:
  - "10.11"

branches:
  only:
    - master

before_script:
  - npm install -g @angular/cli

script:
  - yarn build

notifications:
  email:
    on_failure: change
    on_success: change
